"use client"

import './global.css'
import { Inter } from 'next/font/google'
import { Header, Footer, SplashScreen } from '@/components'
import { usePathname } from "next/navigation"
import { useEffect, useState } from 'react'
import OnboardingScreen from '@/components/onboarding'
import Cookies from 'js-cookie'

const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: './favicon.svg',
    apple: './favicon.svg',
  }
}
  
export const siteMetadata = metadata;

export default function RootLayout({ children }) {
  const pathname = usePathname()
  const isHome = pathname === '/'
  const [loading, setLoading] = useState(isHome)
  // const [showOnboardingScreen, setShowOnboardingScreen] = useState(false)
  const [showOnboardingScreen, setShowOnboardingScreen] = useState(
    Cookies.get('visitedBefore') // Cookie check to see if the user has visited before
    //set it back to false
  )
  useEffect(() => {
    setTimeout(() => {
      setLoading(false)
    }, 3000)
    Cookies.set('visitedBefore', 'true', { expires: 365 }) // Expires after 365 days
  }, [])

  return (
    <html lang="en">
      <body className={inter.className}>
         {loading ?
          <SplashScreen /> :
          <>
            {showOnboardingScreen ? <OnboardingScreen setShowOnboardingScreen={setShowOnboardingScreen} /> :
              <>
                <Header />
                {children}
                <Footer />
              </>}
          </>
        } 
        {/* <OnboardingScreen /> */}
      </body>
    </html>
  )
}
