import './globals.css'
import { Inter } from 'next/font/google'
import { Header, Footer, SplashScreen } from '@/components'
import usePathname from "next/navigation"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const pathname = usePathname()
  const isHome = pathname === '/'
  const [loading, setLoading] = useState(isHome)

  return (
    <html lang="en">
      <body className={inter.className}>
        {loading ?
          <SplashScreen /> :

          <>
            <Header />
            {children}
            <Footer />
          </>
        }

      </body>
    </html>
  )
}
