"use client"

import './global.css'
import { Inter } from 'next/font/google'
import { Header, Footer, SplashScreen } from '@/components'
import { usePathname } from "next/navigation"
import { useEffect, useState } from 'react'
import Cookies from 'js-cookie'
import { ToastContainer } from 'react-toastify';
import { AuthProvider } from '@/context/AuthContext'
import 'react-toastify/dist/ReactToastify.css';
const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: './favicon.svg',
    apple: './favicon.svg',
  }
}
  
export const siteMetadata = metadata;

export default function RootLayout({ children }) {
  const pathname = usePathname()
  const isHome = pathname === '/'
  const [loading, setLoading] = useState(isHome)
  
  const showOnboardScreen = () => {
    setShowOnboardingScreen(false);
  }

  useEffect(() => {    
    setTimeout(() => {
      setLoading(false)
    }, 3000)
    Cookies.set('visitedBefore', 'false', { expires: 365 }) // Expires after 365 days
  }, []);

  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className='sm:hidden'>
            {loading ?
              <SplashScreen/> :
              <>
                {/* {showOnboardingScreen ? <OnboardingScreen resetScreen={showOnboardScreen} /> : */}
                  <>
                    {<ToastContainer/>}
                    {children}
                  </>
                
              </>
            } 
          </div>
        </body>
      </html>
    </AuthProvider>
  )
}
